---
title: "Exploratory Analysis"
author: "Erik Guterman"
date: "3/28/2020"
output: pdf_document
---

```{r}
library(tidyverse)
library(readr)
library(car)
library(lmtest)
library(xgboost)
library(mltools)
library(data.table)
```


Consider separate models for Motion for Summary Judgement and Motion to Dismiss

#Reading in the data. All columns not specified use ReadR's default. 


```{r}
##Many values specified as characters will be later converted to factors, if needed. 
##Additionally, the MUDAC_ID column is left as a CHAR across all datasets for simpler joining.

train_dockets <- read_csv(
  "train_dockets.csv",
  col_types = cols(
  circuit = col_character(),
  district = col_character(),
  diversity_residence = col_character(),
  filers_county = col_character(),
  jurisdiction = col_character(),
  mudac_id = col_character(),
  nos_code = col_character(),
  office = col_character(),
  origin_at_filing = col_character(),
  pro_se = col_character(),
  settled = col_logical(),
  summary_judgment = col_logical()
  )
  )

train_other_motions <-
  read_csv("train_other_motions.csv",
  col_types = cols(mudac_id = col_character()))

train_terminating_motions <-
  read_csv("train_terminating_motions.csv",
  col_types = cols(mudac_id = col_character()))

district_fips_code <- read_csv(
  "district_fips_code.csv",
  col_types = cols(district_number = col_character(),
  fips_code = col_character())
  )
  
districts <-
  read_csv("districts.csv", col_types = cols(district_number = col_character()))
  
```

#Merging Datasets

```{r}
##The dataset we're working with is small enough that we'll be fine merging these together

merged_district_with_fips <-
  left_join(district_fips_code, districts, by = c("district_number", "state")) %>% 
  rename(census_2010_district_population = census_2010_population)

##Also, going to merge this information into the main one just to make it easier for humans to read.  
train_dockets <- left_join(train_dockets, districts, by = c("district" = "district_number"))
```

#Cleaning and transforming data

```{r}
##There are very few cases with any pro se clients, and therefore all will be combined into one in order to improve the availability
train_dockets <- train_dockets %>% 
  mutate(pro_se = ifelse(pro_se == 0, 0, 1))

train_other_motions$decison <- as_factor(train_other_motions$decison)

train_other_motions$terminating <- FALSE
train_terminating_motions$terminating <- TRUE

train_all_motions <- bind_rows(train_other_motions, train_terminating_motions)

unavailableDistricts <- train_other_motions %>% 
  left_join(select(train_dockets, c(
  "mudac_id", "circuit", "district", "office"
  )), by = "mudac_id") %>% filter(is.na(circuit)) %>% 
  select("mudac_id")

```

##Exploratory Analysis

```{r}
ggplot(train_dockets, aes(x = year_filed)) + 
  geom_histogram(bins = 15, colour="black", fill="indianred4")

ggplot(train_dockets,
       aes(x = year_filed,
       fill = outcome)) +
       geom_bar(position = "fill") 

##it might be worth considering a filter for 2020 if we include a year factor in the final model due to the very low number of cases for 2020
##a difference visible in the distribution of outcomes

ggplot(train_dockets, 
       aes(x = district, fill = circuit)) + 
  geom_bar(position = "stack")

summary(glm(summary_judgment ~ circuit, data = train_dockets, family = binomial()))
summary(glm(settled ~ circuit, data = train_dockets, family = binomial()))

##In short, circuit does matter when computing the outcome. 

ggplot(train_dockets, 
       aes(x = nos_code, fill = circuit)) + 
  geom_bar(position = "dodge")

##The huge spike is the Illinois Northern district, which services the city of Chicago 
##Similarly, the second highest is the Eastern Michigan district, representing Detroit, and so on for other large cities

##Ask Barbara what to do with this extreme imbalance
##Anova(lm(train_dockets$nos_code ~ train_dockets$circuit), type = 2)

summary(glm(summary_judgment ~ requested_damages_amt, data = train_dockets, family = binomial()))
summary(glm(settled ~ requested_damages_amt, data = train_dockets, family = binomial()))
##Requested damages isn't a significant predictor of a summary judgement, but increasing it does lead to an increased likelihood of settling.

summary(glm(summary_judgment ~ pro_se, data = train_dockets, family = binomial()))
summary(glm(settled ~ pro_se, data = train_dockets, family = binomial()))
##Filing pro se is a significant predictor of likelihood of both. 

summary(glm(summary_judgment ~ days_opened, data = train_dockets, family = binomial()))
summary(glm(settled ~ days_opened, data = train_dockets, family = binomial()))
##The data may be unbalanced due to the fact that length of trial has a significant effect on outcome, and cases that will last longer that started recently will not have finished yet.  

```

```{r}
train_dockets <-
  train_all_motions %>%
  group_by(mudac_id) %>%
  summarise(nmotionsfiled = n()) %>%
  right_join(train_dockets, by =  "mudac_id") %>%
  mutate(nmotionsfiled = replace_na(nmotionsfiled, 0))

cor(train_dockets$days_opened, train_dockets$nmotionsfiled)

##How to determine which is the better indicator

summary(glm(settled ~ days_opened, data = train_dockets, family = binomial()))
summary(glm(settled ~ nmotionsfiled, data = train_dockets, family = binomial()))

summary(glm(settled ~ nmotionsfiled + days_opened, data = train_dockets, family = binomial()))
summary(glm(settled ~ nmotionsfiled + days_opened, data = train_dockets, family = binomial()))

```

```{r}
train_other_motions %>% filter(!is.na(decison)) %>% 
  left_join(select(train_dockets, c("mudac_id", "circuit", "district", "office")), by = "mudac_id") %>% 
  ggplot(aes(x = circuit, fill = decison)) + 
    geom_bar(position = "fill")

rateAcceptDenyMotionByCourt <- train_other_motions %>% filter(!is.na(decison)) %>%
  left_join(select(train_dockets, c("mudac_id", "district", "office")), by = "mudac_id") %>%
  filter(filing_party != "Unknown" & filing_party != "Other") %>%
  group_by(district, filing_party) %>%
  summarise(
  Count = n(),
  rateGrant = mean(str_detect(decison, "Grant")),
  rateDeny = mean(str_detect(decison, "Denied")),
  rateOther = 1 - (rateGrant + rateDeny)
  )

train_other_motions %>% filter(!is.na(decison)) %>%
  left_join(select(train_dockets, c(
  "mudac_id", "circuit", "district", "office"
  )), by = "mudac_id") %>%
    filter(filing_party == "Defendant") %>% 
  mutate(decison = fct_collapse(
  decison,
  Grant = c("Granted", "Granted in Part"),
  Deny = c("Denied", "Denied as Moot")
  )) %>%
  ggplot(aes(x = circuit, fill = decison)) +
  geom_bar(position = "fill")

train_other_motions %>% filter(!is.na(decison)) %>%
  left_join(select(train_dockets, c(
  "mudac_id", "circuit", "district", "office"
  )), by = "mudac_id") %>%
  filter(filing_party == "Plaintiff") %>% 
  mutate(decison = fct_collapse(
  decison,
  Grant = c("Granted", "Granted in Part"),
  Deny = c("Denied", "Denied as Moot")
  )) %>%
  ggplot(aes(x = circuit, fill = decison)) +
  geom_bar(position = "fill")

##Everyone is nicer to defendants, but especially the 7th circuit. 



```

##Now, the fun XGBoost stuff

```{r}
temp <-
  train_dockets %>% select(nmotionsfiled, district, requested_damages_amt, pro_se) %>%
  mutate(district = as_factor(district)) %>%
  as.data.table()

temp2 <- one_hot(temp) %>% as.matrix() 
label <- train_dockets %>% select(settled) %>% mutate(settled = ifelse(settled == TRUE, 1, 0)) %>% as.matrix()

n <- 100
data <- data.frame(x=runif(n), y=rnorm(n))
ind <- sample(c(TRUE, FALSE), n, replace=TRUE, prob=c(0.5, 0.5))
dataTrain <- temp2[ind, ]
dataTest <- temp2[!ind, ]
labelTrain <- label[ind,]
labelTest <- label[!ind,]

trainData <- xgb.DMatrix(dataTrain, label = labelTrain)
testData <- xgb.DMatrix(dataTest, label = labelTest)
watchlist <- list(train = trainData, eval = testData)
bstSparse <- xgboost(data = trainData, max_depth = 6, eta = 0.3, nthread = 2, nrounds = 10, objective = "binary:logistic")
pred <- predict(bstSparse, trainData)
outcome <- ifelse(pred > 0.5, 1, 0)
mean(outcome == labelTrain)
```









