---
title: "y~all variable except outcome"
author: "Xinyun Li"
date: "3/28/2020"
output: html_document
---
```{r}
library(tidyverse)
library(readr)
library(foreign)
library(nnet)
library(ggplot2)
```

```{r}
train_dockets <- read_csv(
  "train_dockets.csv",
  col_types = cols(
  circuit = col_character(),
  district = col_character(),
  diversity_residence = col_character(),
  filers_county = col_character(),
  jurisdiction = col_character(),
  mudac_id = col_character(),
  nos_code = col_character(),
  office = col_character(),
  origin_at_filing = col_character(),
  pro_se = col_character(),
  settled = col_logical(),
  summary_judgment = col_logical()
  )
  )

train_other_motions <-
  read_csv("train_other_motions.csv",
  col_types = cols(mudac_id = col_character()))
  
train_terminating_motions <-
  read_csv("train_terminating_motions.csv",
  col_types = cols(mudac_id = col_character()))

train_dockets <- read_csv("train_dockets.csv",
  col_types = cols(mudac_id = col_character()))
```

```{R}
train_other_merge <- full_join(train_other_motions,train_dockets,by="mudac_id")
train_terminate_merge <- full_join(train_terminating_motions,train_dockets,by="mudac_id")
```

```{R}
#settled
summary(glm(settled~ motion_type+ filing_party+filed_before_joined+decison+decided_before_joined+proceeding_precentile+circuit+district+office+nos_code+statute+requested_damages_amt+jury_demand+jurisdiction+diversity_residence+participants+plaintiffs+defendants+attorneys_listed+judges_assigned+informa_pauperis+class_action+arbitration_at_filing+origin_at_filing+filers_county+issue_joined+pretrial_conf+total_entry_count+before_ij_entry_count+after_ij_entry_count+year_filed+days_opened,family = binomial,data=train_other_merge))
```

```{R}
summary(glm(settled~ motion_type+ filing_party+filed_before_joined+decison+decided_before_joined+proceeding_precentile+circuit+district+office+nos_code+protected_class+requested_damages_amt+jury_demand+jurisdiction+diversity_residence+participants+plaintiffs+defendants+attorneys_listed+judges_assigned+informa_pauperis+class_action+arbitration_at_filing+origin_at_filing+filers_county+issue_joined+pretrial_conf+total_entry_count+before_ij_entry_count+after_ij_entry_count+year_filed+days_opened,family = binomial,data=train_other_merge))

```

```{R}
#summary_judgement
summary(glm(summary_judgment~motion_type+ filing_party+filed_before_joined+decison+decided_before_joined+proceeding_precentile+circuit+district+office+nos_code+statute+requested_damages_amt+jury_demand+jurisdiction+diversity_residence+participants+plaintiffs+defendants+attorneys_listed+judges_assigned+informa_pauperis+class_action+arbitration_at_filing+origin_at_filing+filers_county+issue_joined+pretrial_conf+total_entry_count+before_ij_entry_count+after_ij_entry_count+year_filed+days_opened,family = binomial,data=train_other_merge))

```

```{R}
#outcome R ABORTED
#outcome_lm <- multinom(outcome~motion_type+ filing_party+filed_before_joined+decison+decided_before_joined+proceeding_precentile+circuit+district+office+nos_code+statute+requested_damages_amt+jury_demand+jurisdiction+diversity_residence+participants+plaintiffs+defendants+attorneys_listed+judges_assigned+informa_pauperis+class_action+arbitration_at_filing+origin_at_filing+filers_county+issue_joined+pretrial_conf+total_entry_count+before_ij_entry_count+after_ij_entry_count+year_filed+days_opened,data=train_other_merge)

#z <- summary(outcome_lm)$coefficients/summary(outcome_lm)$standard.errors
#z

#p <- (1 - pnorm(abs(z), 0, 1)) * 2
#p
```

```{R}
district_settle <- glm(settled~district,data=train_other_merge)
summary(district_settle)
logLik(district_settle)
```

```{R}
district_summary <- glm(summary_judgment~district,data=train_other_merge)
summary(district_summary)
logLik(district_summary)

```

```{R}
circuit_settle <-glm(settled~circuit,data=train_other_merge)
summary(circuit_settle)
logLik(circuit_settle)
```

```{R}
circuit_summary <-glm(summary_judgment~circuit,data=train_other_merge)
summary(circuit_summary)
logLik(district_summary)
```

```{R}
train_terminate_merge <- full_join(train_terminating_motions,train_dockets,by="mudac_id")
head(train_terminate_merge)
```

```{R}
summary(glm(settled~ motion_type+ filing_party+filed_before_joined+proceeding_precentile+circuit+district+office+nos_code+statute+requested_damages_amt+jury_demand+jurisdiction+diversity_residence+participants+plaintiffs+defendants+attorneys_listed+judges_assigned+informa_pauperis+class_action+arbitration_at_filing+origin_at_filing+filers_county+issue_joined+pretrial_conf+total_entry_count+before_ij_entry_count+after_ij_entry_count+year_filed+days_opened,family = binomial,data=train_terminate_merge))
```

```{R}
summary(glm(summary_judgment~ motion_type+ filing_party+filed_before_joined+proceeding_precentile+circuit+district+office+nos_code+statute+requested_damages_amt+jury_demand+jurisdiction+diversity_residence+participants+plaintiffs+defendants+attorneys_listed+judges_assigned+informa_pauperis+class_action+arbitration_at_filing+origin_at_filing+filers_county+issue_joined+pretrial_conf+total_entry_count+before_ij_entry_count+after_ij_entry_count+year_filed+days_opened,family = binomial,data=train_terminate_merge))
```